runtime: nodejs20

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_pending_latency: 1s
  min_pending_latency: 0.5s

entrypoint: npm start 